### ISSUE TITLE
HyperX Cloud Flight S 7.1

### ISSUE THREAD

**Issue by andreluizs** [kondinskis/hyperx-cloud-flight#2]
Hi, doesn't work with _HyperX Cloud Flight S 7.1 Wireless QI- HX-HSCFS-SG/WW_ ?

I followed the steps of README.md and got the following error:

![hyperx](https://user-images.githubusercontent.com/7385294/144649944-98be0330-22f9-4646-a311-676567a0f131.png)

**Comment by kondinskis** [comment]
Right now the app supports only the basic [Cloud Flight version](https://www.hyperxgaming.com/unitedstates/us/headsets/cloud-flight-wireless-gaming-headset).

**Comment by romanvrd** [comment]
Hi. I'm having the exact same issue with my Cloud Flights (non S). This is the output from running the application with the `RUST_BACKTRACE` environment variable:
```
$ env RUST_BACKTRACE=full ./cloud-flight_amd64
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: OpenHidDeviceError', src/cloud_flight.rs:68:53
stack backtrace:
   0:     0x55f63efbe14c - std::backtrace_rs::backtrace::libunwind::trace::h3fea1eb2e0ba2ac9
                               at /rustc/59eed8a2aac0230a8b53e89d4e99d55912ba6b35/library/std/src/../../backtrace/src/backtrace/libunwind.rs:90:5
   1:     0x55f63efbe14c - std::backtrace_rs::backtrace::trace_unsynchronized::h849d83492cbc0d59
                               at /rustc/59eed8a2aac0230a8b53e89d4e99d55912ba6b35/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0x55f63efbe14c - std::sys_common::backtrace::_print_fmt::he3179d37290f23d3
                               at /rustc/59eed8a2aac0230a8b53e89d4e99d55912ba6b35/library/std/src/sys_common/backtrace.rs:67:5
   3:     0x55f63efbe14c - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h140f6925cad14324
                               at /rustc/59eed8a2aac0230a8b53e89d4e99d55912ba6b35/library/std/src/sys_common/backtrace.rs:46:22
   4:     0x55f63efdeaec - core::fmt::write::h31b9cd1bedd7ea38
                               at /rustc/59eed8a2aac0230a8b53e89d4e99d55912ba6b35/library/core/src/fmt/mod.rs:1150:17
   5:     0x55f63efbbfd5 - std::io::Write::write_fmt::h1fdf66f83f70913e
                               at /rustc/59eed8a2aac0230a8b53e89d4e99d55912ba6b35/library/std/src/io/mod.rs:1667:15
   6:     0x55f63efbfcc0 - std::sys_common::backtrace::_print::he7ac492cd19c3189
                               at /rustc/59eed8a2aac0230a8b53e89d4e99d55912ba6b35/library/std/src/sys_common/backtrace.rs:49:5
   7:     0x55f63efbfcc0 - std::sys_common::backtrace::print::hba20f8920229d8e8
                               at /rustc/59eed8a2aac0230a8b53e89d4e99d55912ba6b35/library/std/src/sys_common/backtrace.rs:36:9
   8:     0x55f63efbfcc0 - std::panicking::default_hook::{{closure}}::h714d63979ae18678
                               at /rustc/59eed8a2aac0230a8b53e89d4e99d55912ba6b35/library/std/src/panicking.rs:210:50
   9:     0x55f63efbf877 - std::panicking::default_hook::hf1afb64e69563ca8
                               at /rustc/59eed8a2aac0230a8b53e89d4e99d55912ba6b35/library/std/src/panicking.rs:227:9
  10:     0x55f63efc0374 - std::panicking::rust_panic_with_hook::h02231a501e274a13
                               at /rustc/59eed8a2aac0230a8b53e89d4e99d55912ba6b35/library/std/src/panicking.rs:624:17
  11:     0x55f63efbfe50 - std::panicking::begin_panic_handler::{{closure}}::h5b5e738edf361af7
                               at /rustc/59eed8a2aac0230a8b53e89d4e99d55912ba6b35/library/std/src/panicking.rs:521:13
  12:     0x55f63efbe614 - std::sys_common::backtrace::__rust_end_short_backtrace::h601a115def7987b1
                               at /rustc/59eed8a2aac0230a8b53e89d4e99d55912ba6b35/library/std/src/sys_common/backtrace.rs:141:18
  13:     0x55f63efbfdb9 - rust_begin_unwind
                               at /rustc/59eed8a2aac0230a8b53e89d4e99d55912ba6b35/library/std/src/panicking.rs:517:5
  14:     0x55f63ef07931 - core::panicking::panic_fmt::h7a58c8fffc5559a4
                               at /rustc/59eed8a2aac0230a8b53e89d4e99d55912ba6b35/library/core/src/panicking.rs:101:14
  15:     0x55f63ef07a23 - core::result::unwrap_failed::h1036b5c6eb8030dd
                               at /rustc/59eed8a2aac0230a8b53e89d4e99d55912ba6b35/library/core/src/result.rs:1617:5
  16:     0x55f63ef47932 - cloud_flight::cloud_flight::CloudFlight::new::hda964275fa918511
  17:     0x55f63ef11e4d - cloud_flight::main::hba4aa7b690629d67
  18:     0x55f63ef42623 - std::sys_common::backtrace::__rust_begin_short_backtrace::h6a63ac63b2c38514
  19:     0x55f63ef27619 - std::rt::lang_start::{{closure}}::h23433ce51d90e0b6
  20:     0x55f63efc087a - core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &F>::call_once::h2790017aba790142
                               at /rustc/59eed8a2aac0230a8b53e89d4e99d55912ba6b35/library/core/src/ops/function.rs:259:13
  21:     0x55f63efc087a - std::panicking::try::do_call::hd5d0fbb7d2d2d85d
                               at /rustc/59eed8a2aac0230a8b53e89d4e99d55912ba6b35/library/std/src/panicking.rs:403:40
  22:     0x55f63efc087a - std::panicking::try::h675520ee37b0fdf7
                               at /rustc/59eed8a2aac0230a8b53e89d4e99d55912ba6b35/library/std/src/panicking.rs:367:19
  23:     0x55f63efc087a - std::panic::catch_unwind::h803430ea0284ce79
                               at /rustc/59eed8a2aac0230a8b53e89d4e99d55912ba6b35/library/std/src/panic.rs:129:14
  24:     0x55f63efc087a - std::rt::lang_start_internal::{{closure}}::h3a398a8154de3106
                               at /rustc/59eed8a2aac0230a8b53e89d4e99d55912ba6b35/library/std/src/rt.rs:45:48
  25:     0x55f63efc087a - std::panicking::try::do_call::hf60f106700df94b2
                               at /rustc/59eed8a2aac0230a8b53e89d4e99d55912ba6b35/library/std/src/panicking.rs:403:40
  26:     0x55f63efc087a - std::panicking::try::hb2022d2bc87a9867
                               at /rustc/59eed8a2aac0230a8b53e89d4e99d55912ba6b35/library/std/src/panicking.rs:367:19
  27:     0x55f63efc087a - std::panic::catch_unwind::hbf801c9d61f0c2fb
                               at /rustc/59eed8a2aac0230a8b53e89d4e99d55912ba6b35/library/std/src/panic.rs:129:14
  28:     0x55f63efc087a - std::rt::lang_start_internal::hdd488b91dc742b96
                               at /rustc/59eed8a2aac0230a8b53e89d4e99d55912ba6b35/library/std/src/rt.rs:45:20
  29:     0x55f63ef122f2 - main
  30:     0x7fc848be6b25 - __libc_start_main
  31:     0x55f63ef080ee - _start
  32:                0x0 - <unknown>
```

**Comment by kondinskis** [comment]
Can you check if hidapi is installed on your machine?
- `libhidapi-hidraw0` for debian based distros
- `hidapi` for arch/manjaro

**Comment by romanvrd** [comment]
Sorry, I forgot to mention, I'm running Arch.
Yes, `hidapi` is installed.

**Comment by kondinskis** [comment]
Can you provide output from the following command `lsusb | grep "Kingston"` ?

**Comment by romanvrd** [comment]
```
$ lsusb | grep "Kingston"                     
Bus 001 Device 008: ID 0951:1723 Kingston Technology HyperX Cloud Flight Wireless
```

**Comment by kondinskis** [comment]
Looks like you have different/older version.
- What is your headphones part number?
- What is the color of the led? Red or green ?

**Comment by kondinskis** [comment]
I released new version, can you check it? 
Make sure to change the udev rules file:
`KERNEL=="hidraw*", ATTRS{busnum}=="1", ATTRS{idVendor}=="0951", ATTRS{idProduct}=="16c4", MODE="0666"
KERNEL=="hidraw*", ATTRS{busnum}=="1", ATTRS{idVendor}=="0951", ATTRS{idProduct}=="1723", MODE="0666"`

**Comment by romanvrd** [comment]
Works like a charm. Thanks!
